/*
 * BotScoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.insighttech.nonprod.euc1.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for BotScoreResponseResponseItem type.
 */
public class BotScoreResponseResponseItem {
    private List<BotScoreResponseResponseItemCustomersItem> customers;

    /**
     * Default constructor.
     */
    public BotScoreResponseResponseItem() {
    }

    /**
     * Initialization constructor.
     * @param  customers  List of BotScoreResponseResponseItemCustomersItem value for customers.
     */
    public BotScoreResponseResponseItem(
            List<BotScoreResponseResponseItemCustomersItem> customers) {
        this.customers = customers;
    }

    /**
     * Getter for Customers.
     * @return Returns the List of BotScoreResponseResponseItemCustomersItem
     */
    @JsonGetter("customers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<BotScoreResponseResponseItemCustomersItem> getCustomers() {
        return customers;
    }

    /**
     * Setter for Customers.
     * @param customers Value for List of BotScoreResponseResponseItemCustomersItem
     */
    @JsonSetter("customers")
    public void setCustomers(List<BotScoreResponseResponseItemCustomersItem> customers) {
        this.customers = customers;
    }

    /**
     * Converts this BotScoreResponseResponseItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BotScoreResponseResponseItem [" + "customers=" + customers + "]";
    }

    /**
     * Builds a new {@link BotScoreResponseResponseItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BotScoreResponseResponseItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .customers(getCustomers());
        return builder;
    }

    /**
     * Class to build instances of {@link BotScoreResponseResponseItem}.
     */
    public static class Builder {
        private List<BotScoreResponseResponseItemCustomersItem> customers;



        /**
         * Setter for customers.
         * @param  customers  List of BotScoreResponseResponseItemCustomersItem value for customers.
         * @return Builder
         */
        public Builder customers(List<BotScoreResponseResponseItemCustomersItem> customers) {
            this.customers = customers;
            return this;
        }

        /**
         * Builds a new {@link BotScoreResponseResponseItem} object using the set fields.
         * @return {@link BotScoreResponseResponseItem}
         */
        public BotScoreResponseResponseItem build() {
            return new BotScoreResponseResponseItem(customers);
        }
    }
}
