/*
 * BotScoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.insighttech.nonprod.euc1.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BotScoreResponseResponseItemCustomersItem type.
 */
public class BotScoreResponseResponseItemCustomersItem {
    private BotScoreResponseResponseItemCustomersItemC c;

    /**
     * Default constructor.
     */
    public BotScoreResponseResponseItemCustomersItem() {
    }

    /**
     * Initialization constructor.
     * @param  c  BotScoreResponseResponseItemCustomersItemC value for c.
     */
    public BotScoreResponseResponseItemCustomersItem(
            BotScoreResponseResponseItemCustomersItemC c) {
        this.c = c;
    }

    /**
     * Getter for C.
     * @return Returns the BotScoreResponseResponseItemCustomersItemC
     */
    @JsonGetter("C")
    public BotScoreResponseResponseItemCustomersItemC getC() {
        return c;
    }

    /**
     * Setter for C.
     * @param c Value for BotScoreResponseResponseItemCustomersItemC
     */
    @JsonSetter("C")
    public void setC(BotScoreResponseResponseItemCustomersItemC c) {
        this.c = c;
    }

    /**
     * Converts this BotScoreResponseResponseItemCustomersItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BotScoreResponseResponseItemCustomersItem [" + "c=" + c + "]";
    }

    /**
     * Builds a new {@link BotScoreResponseResponseItemCustomersItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BotScoreResponseResponseItemCustomersItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(c);
        return builder;
    }

    /**
     * Class to build instances of {@link BotScoreResponseResponseItemCustomersItem}.
     */
    public static class Builder {
        private BotScoreResponseResponseItemCustomersItemC c;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  c  BotScoreResponseResponseItemCustomersItemC value for c.
         */
        public Builder(BotScoreResponseResponseItemCustomersItemC c) {
            this.c = c;
        }

        /**
         * Setter for c.
         * @param  c  BotScoreResponseResponseItemCustomersItemC value for c.
         * @return Builder
         */
        public Builder c(BotScoreResponseResponseItemCustomersItemC c) {
            this.c = c;
            return this;
        }

        /**
         * Builds a new {@link BotScoreResponseResponseItemCustomersItem} object using the set
         * fields.
         * @return {@link BotScoreResponseResponseItemCustomersItem}
         */
        public BotScoreResponseResponseItemCustomersItem build() {
            return new BotScoreResponseResponseItemCustomersItem(c);
        }
    }
}
