/*
 * BotScoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package ai.insighttech.nonprod.euc1.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BotScoreResponseResponseItemCustomersItemC type.
 */
public class BotScoreResponseResponseItemCustomersItemC {
    private String bscore;
    private String id;
    private String srcId;

    /**
     * Default constructor.
     */
    public BotScoreResponseResponseItemCustomersItemC() {
    }

    /**
     * Initialization constructor.
     * @param  bscore  String value for bscore.
     * @param  id  String value for id.
     * @param  srcId  String value for srcId.
     */
    public BotScoreResponseResponseItemCustomersItemC(
            String bscore,
            String id,
            String srcId) {
        this.bscore = bscore;
        this.id = id;
        this.srcId = srcId;
    }

    /**
     * Getter for Bscore.
     * Bot Score value (between 0.00 and 1.00)
     * @return Returns the String
     */
    @JsonGetter("bscore")
    public String getBscore() {
        return bscore;
    }

    /**
     * Setter for Bscore.
     * Bot Score value (between 0.00 and 1.00)
     * @param bscore Value for String
     */
    @JsonSetter("bscore")
    public void setBscore(String bscore) {
        this.bscore = bscore;
    }

    /**
     * Getter for Id.
     * ID of customer
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * ID of customer
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for SrcId.
     * Source ID containing bookmaker, sub-bookmaker and customer IDs
     * @return Returns the String
     */
    @JsonGetter("srcId")
    public String getSrcId() {
        return srcId;
    }

    /**
     * Setter for SrcId.
     * Source ID containing bookmaker, sub-bookmaker and customer IDs
     * @param srcId Value for String
     */
    @JsonSetter("srcId")
    public void setSrcId(String srcId) {
        this.srcId = srcId;
    }

    /**
     * Converts this BotScoreResponseResponseItemCustomersItemC into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BotScoreResponseResponseItemCustomersItemC [" + "bscore=" + bscore + ", id=" + id
                + ", srcId=" + srcId + "]";
    }

    /**
     * Builds a new {@link BotScoreResponseResponseItemCustomersItemC.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BotScoreResponseResponseItemCustomersItemC.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(bscore, id, srcId);
        return builder;
    }

    /**
     * Class to build instances of {@link BotScoreResponseResponseItemCustomersItemC}.
     */
    public static class Builder {
        private String bscore;
        private String id;
        private String srcId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  bscore  String value for bscore.
         * @param  id  String value for id.
         * @param  srcId  String value for srcId.
         */
        public Builder(String bscore, String id, String srcId) {
            this.bscore = bscore;
            this.id = id;
            this.srcId = srcId;
        }

        /**
         * Setter for bscore.
         * @param  bscore  String value for bscore.
         * @return Builder
         */
        public Builder bscore(String bscore) {
            this.bscore = bscore;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for srcId.
         * @param  srcId  String value for srcId.
         * @return Builder
         */
        public Builder srcId(String srcId) {
            this.srcId = srcId;
            return this;
        }

        /**
         * Builds a new {@link BotScoreResponseResponseItemCustomersItemC} object using the set
         * fields.
         * @return {@link BotScoreResponseResponseItemCustomersItemC}
         */
        public BotScoreResponseResponseItemCustomersItemC build() {
            return new BotScoreResponseResponseItemCustomersItemC(bscore, id, srcId);
        }
    }
}
